# Generated by Django 6.0.7 on 2026-07-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pickup_date',
            new_name='pickup_datetime',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='return_date',
            new_name='return_datetime',
        ),
    ]
